# Generated by Django 4.1.7 on 2023-03-16 15:16

from django.db import migrations
import plans.models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_plans_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avilableexcercises',
            name='name',
            field=plans.models.LowerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='musclesgroup',
            name='name',
            field=plans.models.LowerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plans',
            name='name',
            field=plans.models.LowerField(max_length=50),
        ),
    ]
