# Generated by Django 4.1.7 on 2023-03-31 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plans.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0005_alter_traninglog_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='name',
        ),
        migrations.CreateModel(
            name='PlanName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', plans.models.LowerField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plans',
            name='planname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plans.planname'),
            preserve_default=False,
        ),
    ]
