# Generated by Django 4.1.7 on 2023-03-31 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_remove_plans_planname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planname',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='excercise',
        ),
    ]
