# Generated by Django 4.1.7 on 2023-05-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_planname_owner_plans_excercise_plans_planname'),
    ]

    operations = [
        migrations.AddField(
            model_name='avilableexcercises',
            name='image',
            field=models.ImageField(default=0, unique=True, upload_to='images/'),
            preserve_default=False,
        ),
    ]
