# Generated by Django 4.1.7 on 2023-05-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_avilableexcercises_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclesgroup',
            name='image',
            field=models.ImageField(default=0, unique=True, upload_to='./images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avilableexcercises',
            name='image',
            field=models.ImageField(unique=True, upload_to='./images'),
        ),
    ]
