# Generated by Django 4.1.7 on 2023-03-08 21:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainerPerson',
            new_name='Trainers',
        ),
    ]
