# Generated by Django 4.1.7 on 2023-03-11 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Trainer', '0003_remove_trainers_traine_trainers_methodsdescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymgoer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trainers',
            name='name',
        ),
        migrations.AddField(
            model_name='gymgoer',
            name='name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainers',
            name='name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
