# Generated by Django 4.1.7 on 2023-03-08 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('Trainer', 'Trains other users'), ('User', 'Is trained by others'))},
        ),
    ]
