# Generated by Django 4.1.7 on 2023-03-08 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('isTrainer', 'Trains other users'), ('isTrained', 'Is trained by others'))},
        ),
    ]
