# Generated by Django 4.1.7 on 2023-03-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accountconfigured',
            field=models.BooleanField(default=False),
        ),
    ]
